window.NOODLES_DEFAULT_CHECKLIST = [
  { section: "FOH Cleaninliness", item: "Floors", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Table", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Booth Dividers", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Booth Seats / Backs", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Cushions and under", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Dine in trays are clean", maxPoints: 2 },
  { section: "FOH Cleaninliness", item: "Glass on Doors & Smudges", maxPoints: 4 },
  { section: "FOH Cleaninliness", item: "Bus Station", maxPoints: 3 },
  { section: "FOH Cleaninliness", item: "Bathrooms (air freshener, clean, stocked)", maxPoints: 4 },
  { section: "FOH Cleaninliness", item: "Temperature in Dining Room", maxPoints: 3 },
  { section: "FOH Cleaninliness", item: "Appropriate Music Playlist At Good Volume", maxPoints: 4 },
  { section: "FOH Cleaninliness", item: "Bussing Tables (15 minutes max)", maxPoints: 2 },

  { section: "Exterior & Patio", item: "Parking Lot / Sidewalks", maxPoints: 4 },
  { section: "Exterior & Patio", item: "Table are Clean", maxPoints: 1 },
  { section: "Exterior & Patio", item: "Umbrellas are up", maxPoints: 1 },
  { section: "Exterior & Patio", item: "Music is on", maxPoints: 1 },
  { section: "Exterior & Patio", item: "Mullions are clean", maxPoints: 1 },

  { section: "BOH", item: "Kitchen Floors", maxPoints: 2 },
  { section: "BOH", item: "Back Area Floors", maxPoints: 2 },
  { section: "BOH", item: "Drains are Clean", maxPoints: 2 },
  { section: "BOH", item: "Drains' Strainers are in place", maxPoints: 1 },
  { section: "BOH", item: "Dish Area", maxPoints: 2 },
  { section: "BOH", item: "Hood", maxPoints: 3 },
  { section: "BOH", item: "Steamers", maxPoints: 3 },
  { section: "BOH", item: "Oven", maxPoints: 3 },
  { section: "BOH", item: "Rethermalizers", maxPoints: 2 },
  { section: "BOH", item: "Ice Machines", maxPoints: 5 },
  { section: "BOH", item: "Coolers", maxPoints: 3 },
  { section: "BOH", item: "Walk in cooler (Floors / Shelves / Slackrack)", maxPoints: 6 },
  { section: "BOH", item: "Walls", maxPoints: 3 },
  { section: "BOH", item: "Grill", maxPoints: 3 },
  { section: "BOH", item: "Scales & Bump bars", maxPoints: 3 },
  { section: "BOH", item: "All Order Screens", maxPoints: 4 },
  { section: "BOH", item: "Mop Sink", maxPoints: 2 },
  { section: "BOH", item: "Sanitizer Buckets (in place and above the ground)", maxPoints: 3 },
  { section: "BOH", item: "Office (Clean & Organized)", maxPoints: 5 },
  { section: "BOH", item: "Deployment Correctly Filled Out", maxPoints: 5 },
  { section: "BOH", item: "Routines", maxPoints: 5 },
  { section: "BOH", item: "Daily Journey", maxPoints: 3 },
  { section: "BOH", item: "All Stations are up to spec", maxPoints: 3 },

  { section: "Food Quality & Safety", item: "Shift ready sheets", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "Cooling Log", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "MOD Walk Thru", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "Ecosure Audit in the last 14 days", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "Noodles Quality", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "Veggies Quality", maxPoints: 5 },
  { section: "Food Quality & Safety", item: "Overall Daydots", maxPoints: 5 },

  { section: "Ambassadors Performance", item: "Greeting guests within 10 seconds", maxPoints: 2 },
  { section: "Ambassadors Performance", item: "Good Handoff of ToGo Orders (i.e. \"Have a great day!\")", maxPoints: 5 },
  { section: "Ambassadors Performance", item: "Ask if Rewards Member", maxPoints: 2 },
  { section: "Ambassadors Performance", item: "If not Rewards Member, offers drink or dessert to sign up", maxPoints: 5 },
  { section: "Ambassadors Performance", item: "Table Touch Backs", maxPoints: 2 },
  { section: "Ambassadors Performance", item: "Overall Friendiness", maxPoints: 2 },
  { section: "Ambassadors Performance", item: "Bags Are Checked off", maxPoints: 4 },
  { section: "Ambassadors Performance", item: "All Online orders are sealed", maxPoints: 1 }
];
